name: Reusable Deploy
on: 
  workflow_call:
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    inputs: 
      artifact-name:
        description: The the name of deployable artifact
        required: false
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: true
jobs:
  deploy:
    outputs: 
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
      - run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: |
          echo "outcome=success" >> $GITHUB_OUTPUT